### ISSUE TITLE
Skip inheritance models without OMIM phenotype number and manual annotation

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/GeneLists#11]
Title says it all.

**Comment by ingkebil** [comment]
Actually, title doesn't say it all.
If manual annotation is present, skip this when no OMIM phenotype number is found.

**Comment by robinandeer** [comment]
I should have a read through of this code sometime

**Comment by ingkebil** [comment]
Yes. After a while it simply becomes a mess and one should take a step back and reevaluate the purpose. For this particular problem I think the code got simplified, which makes it a lot more readable.
