### ISSUE TITLE
Gene list page lists the wrong name for the FullList

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/GeneLists#12]
It seems http://www.clinicalgenomics.se/namnpagenlistor/ lists the wrong description of the acronym when the acronym exists more than once.

**Comment by ingkebil** [comment]
Fixed by naming the FullList to the acronym of the gene list.

e.g. ATX.txt > FullList panel is renamed to ATX

**Comment by robinandeer** [comment]
Perfect :+1:
