### ISSUE TITLE
Header delimiter

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/GeneLists#17]
````
##Database=<ID=cust002-ATX.txt,Version=40.2,Date=20150429,Acronym=ATX,Complete_name=Neutropenia, Spastic Paraplegia, Ataxia,Clinical_db_genome_build=GRCh37.p13
```

The delimiter for the description messes with the delimiter of the Clinical_genome_build. What characters are allowed in this header?

ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Avoid “=“ and “,” and it should be fine.

We can change this to other symbols for the next update, if this is a problem.

/H

On 10 May 2015, at 19:32, Kenny Billiau <notifications@github.com> wrote:

> ##Database=<ID=cust002-ATX.txt,Version=40.2,Date=20150429,Acronym=ATX,Complete_name=Neutropenia, Spastic Paraplegia, Ataxia,Clinical_db_genome_build=GRCh37.p13
> The delimiter for the description messes with the delimiter of the Clinical_genome_build. What characters are allowed in this header?
> 
> ping @henrikstranneheim
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by ingkebil** [comment]
I just removed those symbols for now. It is only a description field, nothing that is used for automation.
