### ISSUE TITLE
Add contig tag to clinical master list

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/GeneLists#20]
Add contig tags to the meta data header of every gene list file. 
This will enable MIP to analyze only relevant contigs in the clinical files. Making the process faster, robust and independent on gene list size. 

This is required for the next MIP minor update (2.4).

contig tags format (basically vcf style):
##contig=<ID=1
###contig=<ID=2
###contig=<ID=3
###contig=<ID=4
###contig=<ID=5
###contig=<ID=6
###contig=<ID=7
###contig=<ID=8
###contig=<ID=9
###contig=<ID=10
###contig=<ID=11
###contig=<ID=12
###contig=<ID=13
###contig=<ID=14
###contig=<ID=15
###contig=<ID=16
###contig=<ID=17
###contig=<ID=18
###contig=<ID=19
###contig=<ID=20
###contig=<ID=21
###contig=<ID=22
###contig=<ID=X
###contig=<ID=Y

**Comment by ingkebil** [comment]
Other VCF style headers only had '##' instead '###'. Could you confirm you really want '###' @henrikstranneheim .

**Comment by ingkebil** [comment]
Also, do the contigs need to be in order?

**Comment by henrikstranneheim** [comment]
It is supposed to be ‘##’.

Order is not important, (MIP will rearrange them per size anyway), although it might be nice for structure.

/H
On 18 Sep 2015, at 11:45, Kenny Billiau <notifications@github.com> wrote:

> Also, do the contigs need to be in order?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
