### ISSUE TITLE
OMIM multiple entries

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/GeneLists#6]
We need to handle multiple entries returned from OMIM.
Following gene symbol returns two OMIM entries: SLC2A1
http://www.omim.org/entry/143090
http://www.omim.org/entry/138140

The API returns two entries:
http://api.omim.org/api/entry/search/?search=approved_gene_symbol:SLC2A1&format=json

Do we merge the contents of both? How do we check which one is relevant?

Now only the first entry is taken into account.

**Comment by robinandeer** [comment]
ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Let's report all for now. 


Skickat från min iPad

**Comment by ingkebil** [comment]
Merging omim entries is not as straightforward as presumed. I get following information from OMIM:
* OMIM_morbid
  - OMIM_phenotype
  - inheritance model

If I merge multiple OMIM entries that seemingly point to the same gene symbol, we will lose OMIM_morbid information and the connection between OMIM_morbid and the phenotype and inheritance models.

I have quickly checked for CMMS how many cases we would have that result in multiple entries and it is only one, the one I first reported: SLC2A1.
So instead of keeping them all and figure out a solution to merge the entries, I suggest we keep the first OMIM entry that has phenotypes. Something that will solve this particular case.

**Comment by henrikstranneheim** [comment]
Great!

Skickat från min iPhone
