### ISSUE TITLE
Integrate manual annotated inheritance models of clinics

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/GeneLists#7]
I got a couple of complaints about the introduction of the automatic annotation, that this doesn't match or removes the manual annotation of the clinics. This happens for phenotypic_disease_model, where the clinics used to annotate the gene with its inheritance model, but now this has moved to a phenotype based approach: 'AD/AR' becomes 'GENESYMBOL:OMIM_phenotype>AD/AR'.

The questions that pop up:
* do we want to introduce a new column in the gene list with a gene specific, a institute specific inheritance model? This would also mean that MIP2 needs to handle this and this implementation should be finished before reruns are started.
* or do we just want to add the manually annotated inheritance model to all phenotypes for this gene? e.g. For CMMS, from the 93 genes that don't get an inheritance model from OMIM, 89 genes have one phenotype, 4 have multiple.

In any case, the clinics that have manual annotation should be informed if we decide something 

What do you think @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Let's talk about this on Friday.


Skickat från min iPad

**Comment by ingkebil** [comment]
Proposed solution for the OMIM inheritance:
When querying OMIM with a HGNC symbol for inheritance models, OMIM returns inheritance models on phenotype level. One gene can have multiple phenotypes which can have multiple inheritance models.
Case 1: When no inheritance model is found, the manual annotation will be used.
Case 2: When multiple phenotypes without inheritance model are found, the manual annotation will be applied to all of them.
Each use of manual annotation will be reported back to the clinic, so they can verify if the reported phenotype can be associated with the manually annotated inheritance model. Ideally, the clinic should report this finding back to OMIM.

When the manual annotation needs to be changed for only one phenotype out of multiple in case 2, I will add a post processing bash script that will make the change. That script can also hold the reference to the ticket where this change was proposed. The bash script should be named after the gene list and placed in a subfolder called postprocessing.
